title: TriEl LTD
email: office@triel.bg
description: TriEl Ltd. is an independent company which was established in year 2000 with main activities “Engineering, Contracting and Consulting” in the field of Electrical Power Supply Projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username: B-V-Vulkov

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs
