# Site settings
title: TriEl Ltd
email: office@triel.bg
description: TriEl Ltd. is an independent company which was established in year 2000 with main activities “Engineering, Contracting and Consulting” in the field of Electrical Power Supply Projects.
destination: docs
baseurl: ""

url: ""
github_username: B-V-Vulkov

# Build settings
future: true
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs
  - _assets
  - gulpfile.js
  - package.json
  - package-lock.json